### ISSUE TITLE
Application crashes when using Orthogonal router and Straight path generator

### ISSUE THREAD

**Issue by rborosak** [Blazor-Diagrams/Blazor.Diagrams#144]
Steps to reproduce.
Create nodes with TopLeft, TopRight, BottomLeft, BottomRight and try to connect two nodes. 
The app will crash with 
 Error: System.NotImplementedException: The method or operation is not implemented.
   at Blazor.Diagrams.Core.Routers.GetOriginSpot(Point p, PortAlignment alignment, Double shapeMargin)
   at Blazor.Diagrams.Core.Routers.Orthogonal(Diagram _, BaseLinkModel link)
   at Blazor.Diagrams.Components.LinkWidget.BuildRenderTree(RenderTreeBuilder __builder)
   
I can see in the source why this is happening. Is this by design or just an oversight?

**Comment by rligocki** [comment]
+1
