### ISSUE TITLE
ZoomIn ZoomOut throws JSException

### ISSUE THREAD

**Issue by VladislavAntonyuk** [Blazor-Diagrams/Blazor.Diagrams#155]
1. ZoomIn, ZoomOut multiple times using the mouse wheel
2. 
```
Error: Microsoft.JSInterop.JSException: Failed to execute 'unobserve' on 'ResizeObserver': parameter 1 is not of type 'Element'.
TypeError: Failed to execute 'unobserve' on 'ResizeObserver': parameter 1 is not of type 'Element'.
    at Object.unobserve (https://localhost:5001/_content/Z.Blazor.Diagrams/script.min.js:1:747)
    at https://localhost:5001/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at It.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:1:3475)
    at https://localhost:5001/_framework/blazor.server.js:1:71331
    at Array.forEach (<anonymous>)
    at It._invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:71317)
    at It._processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:69359)
    at wt.It.connection.onreceive (https://localhost:5001/_framework/blazor.server.js:1:63759)
    at WebSocket.o.onmessage (https://localhost:5001/_framework/blazor.server.js:1:48075)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazor.Diagrams.Extensions.JSRuntimeExtensions.UnobserveResizes(IJSRuntime jsRuntime, ElementReference element)
   at Blazor.Diagrams.Components.Renderers.NodeRenderer.CheckVisibility()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

**Comment by zHaytam** [comment]
I have come to the same conclusion. Although I'm not sure why it started happening only now, I will investigate it more!

**Comment by tomglover24** [comment]
Hi @zHaytam,

I can confirm with default options and a few nodes zooming in and out via scroll or _diagram.SetZoom() functions will trigger this.

Disabling Virtualization seems to be a temporary fix, and WASM performance seems to be comparable.

As a temporary workaround could this be caught in one of the two functions below as all operations seem to be nominal in WASM, even after this has triggered one or more stacktrace's in Console, and the default "Error Banner" appears in the UI.
```
Blazor.Diagrams.Extensions.JSRuntimeExtensions.UnobserveResizes(IJSRuntime jsRuntime, ElementReference element)
Blazor.Diagrams.Components.Renderers.NodeRenderer.CheckVisibility()
```

**Caveat** _I've only tested this with WASM and not Server Side Blazor._

Thanks,
Tom

**Comment by rogue6800** [comment]
I can reproduce this error. Zooming in then error on zooming out on a default installation.

Disabling virtualization also fixed that for me, thanks to @314159265meow for the work around!
