### ISSUE TITLE
InvokeAsync(StateHasChanged) instead of StateHasChanged()

### ISSUE THREAD

**Issue by rob-ack** [Blazor-Diagrams/Blazor.Diagrams#171]
https://github.com/Blazor-Diagrams/Blazor.Diagrams/blob/ef9309c310f26a4828569c26fb8ebefa0278f83b/src/Blazor.Diagrams/Components/DiagramCanvas.razor.cs#L85

I think call's to `StateHasChanged` like linked above should be changed to `InvokeAsync(StateHasChanged);`
This will prevent issues when working with threads and async task based api's

> System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
   at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Blazor.Diagrams.Components.DiagramCanvas.OnDiagramChanged()
   at Blazor.Diagrams.Core.Diagram.Refresh()
   at Blazor.Diagrams.Core.BaseLayer1.Add(T item)
   ...

**Comment by zHaytam** [comment]
Hi, you are absolutely right!
