### ISSUE TITLE
Replacing DragNewBehavior causes RenderLinkTree NullReferenceError

### ISSUE THREAD

**Issue by tarp-jusf** [Blazor-Diagrams/Blazor.Diagrams#389]
I have tried making a custom DragNewBehavior, because I only want to be able to drag links from outgoing Ports.
This results in the RenderLinkTree call to experience a NullReferenceError.

I have tried copying the DragNewBehavior code to check if it was my code, but it also breaks. 
I traced some code while debugging and copied the tracelog up until the error.

```
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 82 of type Blazor.Diagrams.Components.Renderers.PortRenderer
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 59 of type Blazor.Diagrams.Components.DiagramCanvas
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[1]
      Initializing component 90 (Blazor.Diagrams.Components.Renderers.LinkRenderer) as child of 59 (Blazor.Diagrams.Components.DiagramCanvas)
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 90 of type Blazor.Diagrams.Components.Renderers.LinkRenderer
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[1]
      Initializing component 91 (Blazor.Diagrams.Components.LinkWidget) as child of 90 (Blazor.Diagrams.Components.Renderers.LinkRenderer)
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 91 of type Blazor.Diagrams.Components.LinkWidget
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazor.Diagrams.Components.LinkWidget.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by tarp-jusf** [comment]
After looking into this, it seems that DragNewLinkBehavior is being used multiple places. So replacing this behavior will make the whole thing break.
![image](https://github.com/Blazor-Diagrams/Blazor.Diagrams/assets/152276194/f50e765a-2b29-445c-9dfb-ef45ccd9bc21)

A solution could be to change the RegisterBehavior function replace the class associtated with a certain type of behavior.

That way when you use e.g  GetBehavior<DragNewLinkBehavior>, you could get a return of type CustomDragNewLinkBehavior, which can be checked in a if-statement.
![image](https://github.com/Blazor-Diagrams/Blazor.Diagrams/assets/152276194/9339dce1-9b38-4ecf-a402-5e2932b693fc)

**Comment by SergeyIlyin** [comment]
I'm using an external service to create connections. It would be interesting to customize existing behavior.

**Comment by vbalestone** [comment]
@zHaytam thanks for this great library.

I have created some derived behaviors and, to not break so much your implementation I changed the GetBehavior function and,  if the asked one not found, check if has a derived one.
